import { View, Text, ScrollView } from 'react-native'
import React from 'react'

export default function Terms() {
    return (
        <ScrollView style={{ flex: 1 }} contentContainerStyle={{ backgroundColor: "#fff", padding: 4,marginHorizontal:2 }}>
            <Text style={{ textAlign: "center", textTransform: "uppercase", color: "#2246cf", padding: 18 }}>Terms and Conditions</Text>
            <Text style={{ lineHeight: 24, textAlign: "justify" }}>
                Please read the terms and conditions set out below carefully before ordering from this app or website. By ordering any good or services from Feasti via the web, mobile web or through our mobile applications, you agree to be bound by these terms and conditions:{"\n"}
                <Text style={{ fontWeight: "bold" }}>Section 1: Introduction{"\n"}</Text>
                We are Feasti, a brand of Feasti Dash inc., unless otherwise stated.{"\n"}
                <Text style={{ fontWeight: "bold" }}>Section 2: Definitions{"\n"}</Text>
                2.1. ‘Agreement’ is a reference to these terms and conditions, the privacy policy, any order form and payment instructions provided to you;{"\n"}
                2.2. ‘Privacy policy’ means the policy displayed on our website which details how we collect and store your personal data;{"\n"}
                2.3. ‘You’, ‘Your’ and ‘Yours’ are references to you, the person accessing this website and ordering any of our products from the website or any other channels provided by Feasti;{"\n"}
                2.4. ‘We’, ‘Us’, ‘Our’ and ‘Feasti’ are references to the company;{"\n"}
                2.5. ‘Goods’ is a reference to any goods which we may offer for sale from our website from time to time;{"\n"}
                2.6. ‘Service’ or ‘Services’ is a reference to any service which we may supply and which you may request for from us, Feasti;{"\n"}
                2.7. ‘Food delivery’ is a reference to perishable goods and to any form of delivery service, and{"\n"}
                2.8. ‘Website’ and ‘App’ are references to our website http://www.feasti.com or our mobile application through which we offer our goods and services.{"\n"}
                <Text style={{ fontWeight: "bold" }}>Section 3: Ordering{"\n"}</Text>
                3.1. Any contract for the supply of goods and services from this website is between you and Feasti. You agree to take particular care when providing us with your details and warrant that these details are accurate and complete at the time of ordering. You also warrant that the credit or debit card details that you provide are of your own credit or debit card and that you have sufficient funds to make the payment.{"\n"}
                3.2. Any goods and services purchased from this website are intended for your use only and not for resale.{"\n"}
                3.3. When ordering from this Website you may be required to provide an e-mail address and password. You must ensure that you keep the combination of these details secure and do not provide this information to a third party.{"\n"}
                3.4. We will take all reasonable care, in so far as it is in our power to do so, to keep the details of your order and payment secure. During instances of negligence on our part we cannot be held liable for any loss you may suffer if a third party procures unauthorized access to any data you provide when accessing or ordering from the website.{"\n"}
                3.5. Any order that you place with us is subject to product availability, delivery capacity and acceptance by us. When you place your order online, we will send you an auto-generated confirmation mail about the same. You must inform us immediately if any details are incorrect. If the product for which you placed the order is not available or if we are not able to your deliver to your location, we will inform you through a phone call or SMS.{"\n"}
                <Text style={{ fontWeight: "bold" }}>Section 4: Prices and Payment{"\n"}</Text>
                4.1. Any contract for the supply of food items from this website is between you and Feasti. You agree to take particular care when providing us with your details and warrant that these details are accurate and complete at the time of ordering. You also warrant that the credit or debit card details that you provide are for your own credit or debit card and that you have sufficient funds to make the payment.{"\n"}
                4.2. All prices listed on the website are correct at the time of publication. We also reserve the right to alter the product catalogue on the website.{"\n"}
                4.3. All prices for delivery by Feasti or a third party provider assigned by Feasti listed on the website are correct at the time of publication; however, we reserve the right to alter these in the future{"\n"}
                4.4. The total price for the food including taxes will be displayed at the time of checking out your order. Full payment must be made for all items dispatched ordered by online payment, e.g. credit, debit card or bank transfers or in cash.{"\n"}
                4.5. If you choose online payment, you must pay for your order prior to delivery. To ensure that shopping online is secure, your debit/credit card details will be encrypted, thereby preventing the possibility of any third-party accessing your information.{"\n"}
                4.6. If a customer makes payment for the same order more than once by mistake, the extra amount will be refunded via the same gateway to the source within 15 to 20 working days.{"\n"}
                <Text style={{ fontWeight: "bold" }}>Section 5: Delivery{"\n"}</Text>
                5.1. Delivery timings quoted at the time of placing the order are approximate and may vary based on factors such as traffic and weather conditions. The food items you ordered for will be delivered to the address designated by you at the time of placing the order.{"\n"}
                5.2. All orders are delivered by Feasti’s own delivery network or any other reputed delivery service that we may choose to use from time to time. If the Goods are not delivered within the estimated delivery time quoted by us, please contact us by email <Text style={{ textDecorationLine: "underline", color: "#226ccf" }}>support@feasti.com</Text> and we do our best to ensure that you receive your order is delivered as quickly as possible.{"\n"}
                5.3. If you fail to accept your food when it is out for delivery, or if we are unable to deliver at the stated time due to your failure to provide appropriate instructions, or authorizations, then such goods shall be deemed to have been delivered to you and all risk and responsibility in relation to such goods shall pass on to you.{"\n"}
                5.4. You must ensure that at the time of delivery your order adequate arrangements, including access where necessary, are in place for the timely delivery of your order.{"\n"}
                5.5. Feasti will try our best to deliver the product to you at the place of delivery as requested by you in your order within the time confirmed. We will inform you if we are unable to meet the estimated delivery time.{"\n"}
                5.6. Feasti shall not be liable to you for any losses, liabilities, costs, damages, charges or expenses arising out of late delivery.{"\n"}
                5.7. Please note that it might not be possible for us to deliver to some locations. If this is the case, we will inform you using the contact details that you provide to us when you make your order and arrange for cancellation of the order or delivery to an alternative address.{"\n"}
                5.8. In case of the unlikely event of a failed delivery due to reasons beyond the control of the customer, Feasti, will refund the full amount to the customer within will be 15 to 20 working days via the same source by which the payment was made.{"\n"}
                <Text style={{ fontWeight: "bold" }}>Section 6: Cancellation{"\n"}</Text>
                6.1. You must notify Feasti immediately if you decide to cancel your order, preferably by phone, and quote your order number. Orders can be cancelled 12 pm (on the same day for dinner orders) and 6pm (on the previous day).{"\n"}
                6.2. We will not accept any cancellation requests after the cut off period.{"\n"}
                6.3. We may cancel an order if the product is not available for reasons that are not within our control. We will notify you if this is the case and return any payment that you have made.{"\n"}
                6.4. If the cancellation was made in time, we will refund or re-credit your debit or credit card with the full amount within 14 days.{"\n"}
                6.5. In the unlikely event that we deliver a wrong item, you have the right to reject the delivery of the wrong item and you shall be fully refunded for the missing item. If we can only do a partial delivery (a few items might be not available), we would inform you or propose a replacement for missing items. You have the right to refuse a partial order before delivery and get a refund.{"\n"}
                6.6. Meal subscription plans have to be used during the period of validity. In case of the user not availing the meals during the specified period, the meals will lapse. Refund or extension of lapsed plans will not be possible. This is applicable to all subscriptions offered under Meal Plans by Feasti.{"\n"}
                6.7. If you are unsatisfied with the food or unhappy with our services, we will provide you with refund on a pro rata basis i.e., you will be refunded based on the number of meals you have consumed from your subscription given you have already started your subscription. This policy is effective from January, 2022.{"\n"}
                <Text style={{ fontWeight: "bold" }}>Section 7: Information{"\n"}</Text>

                7.1. You agree to provide us with accurate and complete information wherever and whenever we have requested information to provide delivery.{"\n"}
                7.2. You authorize us to use, store or otherwise process your personal information in order to enable the delivery of food items to you and for marketing and credit control purposes. These purposes may include the disclosure of your personal information to selected third parties from time to time where we believe that the services offered by such third parties may be of interest to you or where this is required by law or in order to provide delivery of food items.{"\n"}
                7.3. You are entitled to request a copy of the personal information we hold on you. Please contact us at  <Text style={{ textDecorationLine: "underline", color: "#226ccf" }}>support@feasti.com</Text> if you wish to request this information.{"\n"}
                <Text style={{ fontWeight: "bold" }}>
                    Section 8: Complaints{"\n"}</Text>
                8.1 We take complaints very seriously and aim to address your concerns within 5 business days. All complaints should be sent to <Text style={{ textDecorationLine: "underline", color: "#226ccf" }}>support@feasti.com.{"\n"}</Text>
                <Text style={{ fontWeight: "bold" }}>
                    Section 9: Limitation of Liability{"\n"}
                </Text>
                9.1. Great care has been taken to ensure that the information available on this website is correct and error free. We apologize for any errors or omissions that may have occurred. We cannot warrant that use of the website will be error-free or fit for purpose, timely, that defects will be corrected, or that the site or the server that makes it available are free of viruses or bugs or represents the full functionality, accuracy, reliability of the website and we do not make any warranty whatsoever, whether express or implied, relating to fitness for purpose, or accuracy.{"\n"}
                9.2. By accepting these terms of use, you agree to relieve us from any liability whatsoever arising from your use of information from any third party, or your use of any third party website, or your consumption of any food or beverages ordered from us.{"\n"}
                9.3. We disclaim any and all liability to you for the supply of the food items to the fullest extent permissible under applicable law. This does not affect your statutory rights as a consumer. If we are found liable for any loss or damage to you such liability is limited to the amount you have paid for the relevant items. We cannot accept any liability for any loss, damage or expense, including any direct or indirect loss such as loss of profits to you, howsoever arising. This limitation of liability does not apply to personal injury or death arising as a direct result of our negligence.{"\n"}
                9.4. We do not accept any liability for any delays, failures, errors or omissions or loss of transmitted information, viruses or other contamination or destructive properties transmitted to you or your computer system via our Website.{"\n"}
                9.5. We shall not be held liable for any failure or delay in delivering food items where such failure arises as a result of any act or omission, which is outside our reasonable control such as all overwhelming and unpreventable events caused directly and exclusively by forces of nature that can be neither anticipated, nor controlled, nor prevented by the exercise of prudence, diligence, and care, including but not limited to: war, riot, civil commotion; compliance with any law or governmental order, rule, regulation or direction and acts of third parties.{"\n"}
                9.6. If we have contracted to provide identical or similar order to more than one customer and are prevented from fully meeting our obligations to you by reason of an event of force majeure, we may decide at our absolute discretion which orders we will fill and to what extent.{"\n"}
                9.7. The products sold by us are provided for private domestic and consumer use only. Accordingly, we do not accept liability for any indirect loss, consequential loss, loss of data, loss of income or profit, loss of damage to property and/or loss from claims of third parties arising out of the use of the website or for any products or services purchased from us.{"\n"}
                9.8. We have taken all reasonable steps to prevent Internet fraud and ensure that any data collected from you is stored as securely and safely as possible. However, we cannot be held liable in the extremely unlikely event of a breach in our secure computer servers or those of third parties.{"\n"}
                9.9. In the event Feasti has a reasonable belief that there exists an abuse of vouchers and/or discount codes or in suspected instances of fraud, Feasti may cause the shopper (or customer) to be blocked immediately and reserves the right to refuse future service. Additionally, should there exist an abuse of vouchers or discount codes, Feasti reserves the right to seek compensation from any and all violators.{"\n"}
                9.10. Feasti will do everything in its capacity to maintain the quality of food supplied we supply. However in the unlikely event of poor quality of food reported by a customer, Feasti customer support team will take the majority opinion of the customers to whom the same food was delivered on the given day. If a wide spread quality issue exists, we will consider the issue and handle it accordingly.{"\n"}


            </Text>
        </ScrollView>
    )
}